#!/bin/bash -e
#
# --------------------------------------------------
#
# Script to define environment variables for the run 
#
# --------------------------------------------------
# Configuration architecture
# --------------------------------------------------
# $HOME/CONFIGS/MYCONFIG
#                       - wrf_in
#                       - ww3_in
#                       - croco_in
#                       - oasis_in
# $WORKDIR/CONFIGS/MYCONFIG
#                       - wrf_files
#                       - ww3_files
#                       - croco_files
#                       - oasis_files
# --------------------------------------------------
#
# Further Information:   
# http://www.croco-ocean.org
#  
# This file is part of CROCOTOOLS
#
# CROCOTOOLS is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License,
# or (at your option) any later version.
#
# CROCOTOOLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA
#
# Copyright (c) 2018 S. Jullien
# swen.jullien@ifremer.fr
# S. Jullien, 2018
# swen.jullien@ifremer.fr
# --------------------------------------------------

echo '-- In - run_env ----------------------------'

# check shell is bash (requested to source this script...)
# --------------------------
echo $BASH

export NETCDF=$(nf-config --prefix)

# HOME directory of your machine
# (where you will store scripts and model sources)
# --------------------------
CPL_HOME=/work/0/gf36/f36003/CROCO/USeast_201801/main.L

# WORK/SCRATCH general directory of your machine
# (where you will run the models)
# --------------------------
CPL_WORKDIR=/work/0/gf36/f36003/CROCO/USeast_201801/work.L

# Home and Work configuration directories
# --------------------------
echo 'define Home and Work configuration directories'
export hconf=$CPL_HOME/config
export wconf=$CPL_WORKDIR

# Model sources directory
# --------------------------
echo 'define Model sources directories'
export wrf=$CPL_HOME/wrf/WRFV3
export croco=$CPL_HOME/croco
export ww3=$CPL_HOME/ww3/model
export oasisdir=/work/0/gf36/f36003/OASIS/comp


# Input large files directories
# --------------------------
echo 'define large files inputs dir'
export OASIS_FILES_DIR=$wconf/oasis_files
export WRF_FILES_DIR=$wconf/wrf_files
export WW3_FILES_DIR=$wconf/ww3_files
export CROCO_FILES_DIR=$wconf/croco_files
echo 'define data dir'
export DATA_DIR=$CPL_WORKDIR/DATA

# Settings files directories
# --------------------------
echo 'define settings input dir'
export OASIS_IN_DIR=$CPL_HOME/oasis_in
export WRF_IN_DIR=$CPL_HOME/wrf_in/inputs_wrf
export WW3_IN_DIR=$CPL_HOME/ww3_in
export CROCO_IN_DIR=$CPL_HOME/croco_in

# Cheking run_env
# --------------------------
if [ -d "$CPL_HOME" ]; then
 echo 'define CPL_HOME dir as '$CPL_HOME
else
 echo 'ERROR CPL_HOME: '$CPL_HOME' directory does not exist'
 exit 1
fi

if [ -d "$CPL_WORKDIR" ]; then
 echo 'define CPL_WORKDIR dir as '$CPL_WORKDIR
else
 echo 'ERROR CPL_WORKDIR: '$CPL_WORKDIR' directory does not exist'
 exit 1
fi

if [ -d "$hconf" ]; then
 echo 'define hconf dir as '$hconf
else
 echo 'ERROR hconf: '$hconf' directory does not exist'
 exit 1
fi

if [ -d "$wconf" ]; then
 echo 'define wconf dir as '$wconf
else
 echo 'ERROR wconf: '$wconf' directory does not exist'
 exit 1
fi

if [ -d "$oasisdir" ]; then
 echo 'define oasisdir dir as '$oasisdir
else
 echo 'ERROR oasisdir: '$oasisdir' directory does not exist'
 exit 1
fi

if [ -d "$wrf" ]; then
 echo 'define wrf dir as '$wrf
else
 echo 'WARNING wrf: '$wrf' directory does not exist'
fi

if [ -d "$croco" ]; then
 echo 'define croco dir as '$croco
else
 echo 'WARNING croco: '$croco' directory does not exist'
fi

if [ -d "$ww3" ]; then
 echo 'define ww3 dir as '$ww3
else
 echo 'WARNING ww3: '$ww3' directory does not exist'
fi

if [ -d "$OASIS_FILES_DIR" ]; then
 echo 'define OASIS_FILES_DIR dir as '$OASIS_FILES_DIR
else
 echo 'ERROR OASIS_FILES_DIR: '$OASIS_FILES_DIR' directory does not exist'
 exit 1
fi

if [ -d "$WRF_FILES_DIR" ]; then
 echo 'define WRF_FILES_DIR dir as '$WRF_FILES_DIR
else
 echo 'WARNING WRF_FILES_DIR: '$WRF_FILES_DIR' directory does not exist'
fi

if [ -d "$CROCO_FILES_DIR" ]; then
 echo 'define CROCO_FILES_DIR dir as '$CROCO_FILES_DIR
else
 echo 'WARNING CROCO_FILES_DIR: '$CROCO_FILES_DIR' directory does not exist'
fi

if [ -d "$WW3_FILES_DIR" ]; then
 echo 'define WW3_FILES_DIR dir as '$WW3_FILES_DIR
else
 echo 'WARNING WW3_FILES_DIR: '$WW3_FILES_DIR' directory does not exist'
fi

if [ -d "$OASIS_IN_DIR" ]; then
 echo 'define OASIS_IN_DIR dir as '$OASIS_IN_DIR
else
 echo 'ERROR OASIS_IN_DIR: '$OASIS_IN_DIR' directory does not exist'
 exit 1
fi

if [ -d "$WRF_IN_DIR" ]; then
 echo 'define WRF_IN_DIR dir as '$WRF_IN_DIR
else
 echo 'WARNING WRF_IN_DIR: '$WRF_IN_DIR' directory does not exist'
fi

if [ -d "$CROCO_IN_DIR" ]; then
 echo 'define CROCO_IN_DIR dir as '$CROCO_IN_DIR
else
 echo 'WARNING CROCO_IN_DIR: '$CROCO_IN_DIR' directory does not exist'
fi

if [ -d "$WW3_IN_DIR" ]; then
 echo 'define WW3_IN_DIR dir as '$WW3_IN_DIR
else
 echo 'WARNING WW3_IN_DIR: '$WW3_IN_DIR' directory does not exist'
fi

echo '-- End - run_env ---------------------------'

